export type PosSaleItem = {
  id: string;
  name: string;
  price: number;
  costPrice?: number;
  quantity: number;
  discount?: number;
  itemType?: "repair_service" | "labour" | "diagnosis" | "inspection" | "replacement_part" | "software" | "cleaning" | "other";
  partCode?: string;
  warranty?: string;
  notes?: string;
  repairPartId?: string;
};

export type PosSaleDevice = {
  id: string;
  repairId?: string;
  deviceNumber: string;
  deviceName: string;
  deviceType: string;
  deviceBrand?: string;
  deviceModel?: string;
  deviceSerialNumber?: string;
  faultDescription?: string;
  priority?: "low" | "medium" | "high" | "urgent";
  technician?: string;
  repairStatus?: string;
  estimatedCompletion?: string;
  amount: number;
};

export type PosSale = {
  id: string;
  date: string;
  items: PosSaleItem[];
  subtotal: number;
  discount?: number;
  taxRate?: number;
  tax: number;
  total: number;
  paymentMethod: string;
  customerId?: string;
  customerName?: string;
  customerPhone?: string;
  customerAddress?: string;
  paidAmount?: number;
  pendingBalance?: number;
  cashierId?: string;
  cashierName?: string;
  cashierRole?: "admin" | "employee";
  shiftId?: string;
  repairId?: string;
  repairIds?: string[];
  deviceNumber?: string;
  deviceName?: string;
  deviceBrand?: string;
  deviceModel?: string;
  deviceSerialNumber?: string;
  devices?: PosSaleDevice[];
  faultDescription?: string;
  invoiceStatus?: "unpaid" | "partially_paid" | "paid" | "cancelled";
  priority?: "low" | "medium" | "high" | "urgent";
  technician?: string;
  estimatedCompletion?: string;
  termsAndConditions?: string;
  invoiceType?: "repair" | "sale";
  repairStatus?: string;
  repairProgress?: number;
  diagnosis?: string;
  repairWorkPerformed?: string;
  customerNote?: string;
  status?: "completed" | "cancelled" | "refunded";
  updatedAt?: string;
  cancelledAt?: string;
  refundedAt?: string;
};

export type HeldPosSale = {
  id: string;
  heldAt: string;
  items: PosSaleItem[];
  discount: number;
  taxRate: number;
  paymentMethod: string;
  customerId?: string;
  paidAmount?: number;
};
